### ISSUE TITLE
How in the earth do I set the production settings?

### ISSUE THREAD

**Issue by sabbajohn** [RazAbk/MoneyPipe#2]
I'm trying to host it in another machine and access remotely, but no success

**Comment by RazAbk** [comment]
What I do is, host the app in an external service, such as Heroku, and it holds and deploys my app and service.
I think what you need to look for, is how to deploy an Express.js app.
(The Express app also serves the client side)

Also, it is configured as a PWA app, which might make it more difficult to deploy.
(As I remember when I deployed it)
